
mci_dashboard:
    path:     /
    defaults: { _controller: MciCoreBundle:Default:index }

mci_patient:
    resource: "@MciPatientBundle/Resources/config/routing.yml"
    prefix:   /patients

mci_user:
    resource: "@MciUserBundle/Resources/config/routing.yml"
    prefix:   /

mci_core:
    resource: "@MciCoreBundle/Resources/config/routing.yml"
    prefix:   /

