security:
 encoders:
        Symfony\Component\Security\Core\User\User: plaintext
 providers:
        sso:
          id: sso_provider

 firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            simple-preauth:
                authenticator: sso_authenticator

 role_hierarchy:
        ROLE_MCI_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_MCI_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

 access_control:
        - { path: ^/*, roles: [ROLE_MCI_USER] }

