security:
 encoders:
        Symfony\Component\Security\Core\User\User: plaintext
 providers:
        sso:
          id: sso_user_provider

 firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
            security: false
        default:
            anonymous: ~
            http_basic: ~
            simple_form:
                authenticator: sso_authenticator
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
                default_target_path: mci_dashboard
                always_use_default_target_path: true
                use_referer: true
            logout:
                path:   /logout
                target: /

 role_hierarchy:
        ROLE_MCI_ADMIN:    ROLE_USER
        ROLE_MCI_APPROVER:    ROLE_USER

 access_control:
        - { path: ^/pendingapproval, roles: [ROLE_MCI_APPROVER] }
        - { path: ^/*, roles: [ROLE_USER] }

