
mci_patient_searchpage:
    path:     /search
    defaults: { _controller: MciPatientBundle:Patient:search }


mci_patient_showpage:
    path:     /{id}/show/
    defaults: { _controller: MciPatientBundle:Patient:show }

mci_patient_edit:
    path:     /{id}/edit/
    defaults: { _controller: MciPatientBundle:Patient:edit }
    methods:   [GET]
    requirements:
           id:  \d+

mci_patient_update:
    path:     /{id}/update/
    defaults: { _controller: MciPatientBundle:Patient:update }
    methods:   [POST]

mci_patient_relation_remove:
    path:     /{id}/relation/remove/
    defaults: { _controller: MciPatientBundle:Patient:removeRelation }
    methods:   [POST]

mci_patient_pending_approval:
    path:     /pendingapproval/{dir}/{marker}
    defaults: { _controller: MciPatientBundle:Patient:pendingApproval,  marker: null, dir : next }
    requirements:
        dir:  after|before

mci_patient_approval_details:
    path:     /pendingapproval/details/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalDetails }

mci_patient_approval_accept:
    path:     /pendingapproval/accept/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalAccept }

mci_patient_approval_reject:
    path:     /pendingapproval/reject/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalReject }

mci_patient_audit_log:
    path:     /auditlog/{hid}
    defaults: { _controller: MciPatientBundle:Patient:auditLog }

mci_patient_deduplication:
    path:     /de-duplication/{dir}/{marker}
    defaults: { _controller: MciPatientBundle:Patient:deduplication,  marker: null, dir : next }

mci_patient_deduplication_details:
    path:     /de-duplication/details/{hid1}/{hid2}
    defaults: { _controller: MciPatientBundle:Patient:deduplicationDetails }

mci_patient_deduplication_distinct:
    path:     /de-duplication-distinct
    defaults: { _controller: MciPatientBundle:Patient:dedupDistinct }

mci_patient_deduplication_merge:
    path:     /de-duplication-merge
    defaults: { _controller: MciPatientBundle:Patient:dedupMerge }
    methods:   [POST]
