
mci_patient_searchpage:
    path:     /search
    defaults: { _controller: MciPatientBundle:Patient:search }


mci_patient_showpage:
    path:     /{id}/show/
    defaults: { _controller: MciPatientBundle:Patient:show }

mci_patient_edit:
    path:     /{id}/edit
    defaults: { _controller: MciPatientBundle:Patient:edit }
    methods:   [GET]
    requirements:
           id:  \d+

mci_patient_update:
    path:     /update
    defaults: { _controller: MciPatientBundle:Patient:update }
    methods:   [PUT|POST]

