
mci_patient_searchpage:
    path:     /search
    defaults: { _controller: MciPatientBundle:Patient:search }


mci_patient_showpage:
    path:     /{id}/show/
    defaults: { _controller: MciPatientBundle:Patient:show }

mci_patient_edit:
    path:     /{id}/edit/
    defaults: { _controller: MciPatientBundle:Patient:edit }
    methods:   [GET]
    requirements:
           id:  \d+

mci_patient_update:
    path:     /{id}/update/
    defaults: { _controller: MciPatientBundle:Patient:update }
    methods:   [POST]

mci_patient_relation_remove:
    path:     /{id}/relation/remove/
    defaults: { _controller: MciPatientBundle:Patient:removeRelation }
    methods:   [POST]

mci_patient_pending_approval:
    path:     /pendingApproval/{lastItemId}
    defaults: { _controller: MciPatientBundle:Patient:pendingApproval,  lastItemId: null }

mci_patient_approval_details:
    path:     /pendingApproval/details/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalDetails }

