
mci_patient_searchpage:
    path:     /search
    defaults: { _controller: MciPatientBundle:Patient:search }


mci_patient_showpage:
    path:     /{id}/show/
    defaults: { _controller: MciPatientBundle:Patient:show }

mci_patient_edit:
    path:     /{id}/edit/
    defaults: { _controller: MciPatientBundle:Patient:edit }
    methods:   [GET]
    requirements:
           id:  \d+

mci_patient_update:
    path:     /{id}/update/
    defaults: { _controller: MciPatientBundle:Patient:update }
    methods:   [POST]

mci_patient_relation_remove:
    path:     /{id}/relation/remove/
    defaults: { _controller: MciPatientBundle:Patient:removeRelation }
    methods:   [POST]

mci_patient_pending_approval:
    path:     /pendingapproval
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalNext,  after: null }

mci_patient_pending_approval_next:
    path:     /pendingapprovalnext/{after}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalNext,  after: null }

mci_patient_pending_approval_previous:
    path:     /pendingapprovalprevious/{before}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalPrevious,  before: null }

mci_patient_approval_details:
    path:     /pendingapproval/details/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalDetails }

mci_patient_approval_accept:
    path:     /pendingapproval/accept/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalAccept }

mci_patient_approval_reject:
    path:     /pendingapproval/reject/{hid}
    defaults: { _controller: MciPatientBundle:Patient:pendingApprovalReject }


