services:
    mci_patient.client:
          class: %guzzle.client.class%
          tags:
                      -  { name: guzzle.client }
          calls:
                      - [addSubscriber, ["@mci_auth"]]



    mci.twig.mci_extension:
        class: Mci\Bundle\PatientBundle\Twig\MciExtension
        tags:
            - { name: twig.extension }

    mci.location:
        class:        Mci\Bundle\PatientBundle\Services\Location
        arguments: ["@service_container"]

    mci.patient:
        class:        Mci\Bundle\PatientBundle\Services\Patient
        arguments: ["@service_container", %api_end_point%]
