services:
    mci_patient.client:
        class:     %guzzle.client.class%
        public: false
        arguments:
              - %api_endpoint%
        calls:
          - [ setDefaultOption, [ 'headers/content-type', 'application/json' ] ]
        tags:
          - { name: guzzle.client }

    mci.master_data:
        class: Mci\Bundle\PatientBundle\Services\MasterData
        arguments: [@file_locator]

    mci.twig.mci_extension:
        class: Mci\Bundle\PatientBundle\Twig\MciExtension
        arguments: [ @mci.location, @mci.master_data]
        tags:
            - { name: twig.extension }

    mci.location:
        class:        Mci\Bundle\PatientBundle\Services\Location
        arguments: [@mci_patient.client, @security.context]
        calls:
          - [ setCache, [ @patient_cache ] ]

    mci.patient:
        class:        Mci\Bundle\PatientBundle\Services\Patient
        arguments: [@mci_patient.client, @jms_serializer, @security.context, @mci.twig.mci_extension]
        calls:
          - [ setCache, [ @location_cache ] ]

