services:
    mci_patient.client:
          class: %guzzle.client.class%
          tags:
                      -  { name: guzzle.client }

    mci.twig.mci_extension:
        class: Mci\Bundle\PatientBundle\Twig\MciExtension
        arguments: [ @mci.location, %api_end_point%]
        tags:
            - { name: twig.extension }

    mci.location:
        class:        Mci\Bundle\PatientBundle\Services\Location
        arguments: [@mci_patient.client, %api_end_point%,@security.context]

    mci.patient:
        class:        Mci\Bundle\PatientBundle\Services\Patient
        arguments: [@mci_patient.client, @jms_serializer, %api_end_point%,@security.context]
