services:
#    mci_core.example:
#        class: Mci\Bundle\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    sso_authenticator:
        class:     Mci\Bundle\CoreBundle\Security\SsoUserAuthenticator
        arguments: [ @sso_client ]

    sso_provider:
        class:     Mci\Bundle\CoreBundle\Security\SsoUserProvider
        arguments: [ @sso_client ]

    sso_client:
        class:     Mci\Bundle\CoreBundle\Service\SsoClient
        arguments: [ @guzzle.client,@jms_serializer,%identity_server_domain%,%identity_server_port%]

    mci.session.listener:
        class: Mci\Bundle\CoreBundle\Security\SecurityListener
        arguments: [%identity_server_domain%, %identity_server_port%]
        calls:
            - [ setRouter, [@router] ]
            - [ setSecurityContext, [@security.context] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
